services:
  # Developer container
  dev-container:
    build:
      context: .
    volumes:
      - ./workspace:/workspace
      - /var/run/docker.sock:/var/run/docker.sock  # Access Docker from inside the container
    ports:
      - "8080:8080"  # For web apps
      - "3000:3000"  # Node.js apps
      - "5000:5000"  # Python apps
    tty: true
    depends_on:
      - mysql
      - jenkins

  # MySQL database service
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Jenkins service
  jenkins:
    image: jenkins/jenkins:lts  # Use the latest Jenkins LTS version
    container_name: jenkins
    environment:
      JENKINS_ADMIN_USER: admin
      JENKINS_ADMIN_PASSWORD: adminpassword  # Set your Jenkins admin password
    ports:
      - "8082:8080"  # Exposing Jenkins UI on port 8081
    volumes:
      - jenkins_home:/var/jenkins_home  # Persist Jenkins data
    tty: true

volumes:
  db_data:
  jenkins_home:
